version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: smart-link-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_link
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/database/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
    restart: unless-stopped
    networks:
      - smart-link-network

  redis:
    image: redis:7-alpine
    container_name: smart-link-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis --appendonly yes
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - smart-link-network

networks:
  smart-link-network:
    name: smart-link-network
    driver: bridge
