version: '3.8'

services:
  auth-service:
    image: igorvz/smart-link:latest
    container_name: smart-link-auth
    ports:
      - "3010:3010"
    env_file:
      - .env-auth
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: ["node", "dist/apps/auth/main"]
    networks:
      - smart-link-network

  api-gateway:
    image: igorvz/smart-link:latest
    container_name: smart-link-gateway
    ports:
      - "3020:3020"
    env_file:
      - .env-gateway
    depends_on:
      - auth-service
      - smart-link-service
    restart: unless-stopped
    command: ["node", "dist/apps/api-gateway/main"]
    networks:
      - smart-link-network

  smart-link-service:
    image: igorvz/smart-link:latest
    container_name: smart-link-service
    ports:
      - "3030:3030"
    env_file:
      - .env-smart-link
    depends_on:
      - db
    restart: unless-stopped
    command: ["node", "dist/apps/smart-link/main"]
    networks:
      - smart-link-network

  db:
    image: postgres:16-alpine
    container_name: smart-link-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smart_link
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./src/database/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
    restart: unless-stopped
    networks:
      - smart-link-network

  redis:
    image: redis:7-alpine
    container_name: smart-link-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass redis --appendonly yes
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - smart-link-network

networks:
  smart-link-network:
    name: smart-link-network
    driver: bridge
